class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'megadl1'
        self.UnzipMirrorCommand = 'munzip'
        self.TarMirrorCommand = 'tarmega'
        self.CancelMirror = 'mcancelq'
        self.CancelAllCommand = 'mcancelall1'
        self.ListCommand = 'list'
        self.StatusCommand = 'mstatus1'
        self.AuthorizedUsersCommand = 'musers1'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'mrestart1'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch'
        self.TarWatchCommand = 'tarwatch'
        self.DeleteCommand = 'del'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
